#!/bin/bash
echo "running argocd backup for `date`"

ARGO_NAMESPACE="argo-cd"
FORMATTED_DATE=$(date +%Y-%m-%d) 
TMPDIR="argocd-$FORMATTED_DATE"
BACKUP_DIR="/backup/argo-cd"

main() {
  mkdir /tmp/$TMPDIR

  for I in $(kubectl get application -n $ARGO_NAMESPACE | grep -v "SYNC STATUS" | awk '{print $1}')
  do
    kubectl get application $I -n $ARGO_NAMESPACE -o yaml > /tmp/$TMPDIR/application-$I.yaml
  done

  for I in $(kubectl get appproject -n argo-cd | grep -v NAME | awk '{print $1}')
  do
    kubectl get appproject $I -n $ARGO_NAMESPACE -o yaml > /tmp/$TMPDIR/appproject-$I.yaml
  done

  tar -zvcf - -C /tmp $TMPDIR | gpg -e -o $BACKUP_DIR/argocd-$FORMATTED_DATE.tar.gz.gpg
  find $BACKUP_DIR -name "argocd*.*" -mtime +30 -exec rm -f {} \;

  chmod 755 $BACKUP_DIR/*
}

cleanup () {
  rm -rf /tmp/$TMPDIR &> /dev/null  
}

trap cleanup EXIT ERR INT TERM

main