#!/bin/bash
echo "running vaultwarden backup for `date`"

BACKUP_DIR="/backup/vaultwarden"
FORMATTED_DATE=$(date +%Y-%m-%d)

main() {
  tar -zvcf - -C /kubernetes vaultwarden | gpg -e -o $BACKUP_DIR/vaultwarden-$FORMATTED_DATE.tar.gz.gpg

  find $BACKUP_DIR -name "vaultwarden*.*" -mtime +30 -exec rm -f {} \;

  chmod 755 $BACKUP_DIR/*
}

main