#!/bin/bash
echo "running gitlab-secrets backup for `date`"

GITLAB_NAMESPACE="gitlab"
FORMATTED_DATE=$(date +%Y-%m-%d) 
TMPDIR="gitlab-secrets-$FORMATTED_DATE"
BACKUP_DIR="/backup/gitlab-secrets"

main() {
  mkdir /tmp/$TMPDIR

  for I in $(kubectl get secret -n $GITLAB_NAMESPACE | grep -v "NAME" | awk '{print $1}')
  do
    kubectl get secret $I -n $GITLAB_NAMESPACE -o yaml > /tmp/$TMPDIR/$I.yaml
  done

  tar -zvcf - -C /tmp $TMPDIR | gpg -e -o $BACKUP_DIR/gitlab-secrets-$FORMATTED_DATE.tar.gz.gpg
  find $BACKUP_DIR -name "gitlab-secrets*.*" -mtime +30 -exec rm -f {} \;

  chmod 660 $BACKUP_DIR/*
}

cleanup () {
  rm -rf /tmp/$TMPDIR >/dev/null  
}

trap cleanup EXIT ERR INT TERM

main