#!/bin/bash
echo "running images backup for `date`"
BACKUP_DIR="/backup"
FORMATTED_DATE=$(date +%Y-%m-%d)

tar -cvzf - /images | gpg -e -o $BACKUP_DIR/images-$FORMATTED_DATE.tar.gz.gpg

chmod 775 $BACKUP_DIR/images-$FORMATTED_DATE.tar.gz

find $BACKUP_DIR -name "images*.tar.gz.gpg" -mtime +8 -exec rm -f {} \;
