#!/bin/bash
echo "running images backup for `date`"
BACKUP_DIR="/backup"
FORMATTED_DATE=$(date +%Y-%m-%d)

tar -zcf $BACKUP_DIR/images-$FORMATTED_DATE.tar.gz /images

chmod 775 $BACKUP_DIR/images-$FORMATTED_DATE.tar.gz

find $BACKUP_DIR -name "images*.tar.gz" -mtime +8 -exec rm -f {} \;
